name: Rust Workspace CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup component add --toolchain stable rustfmt rust-src
          rustup default stable

      - name: Check formatting
        run: |
          cargo fmt --all -- --check

      - name: Lint with clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: |
          cargo build --verbose

      - name: Run tests
        run: |
          cargo test --verbose
